### ISSUE TITLE
version of nodemcu to use

### ISSUE THREAD

**Issue by carnife-x** [naztronaut/dancyPi-audio-reactive-led#19]
I'm new to electronics,but have all the components to create this setup except the nodemcu version 3(I have nodemcu version 2).
will there be a problem if i use version 2?

**Comment by naztronaut** [comment]
I looked at the specs for NodeMCU V2, it should be fine. Even the GPIO pins seem similar. The hardware may be a bit slower but that shouldn't be an issue. 

If you do try into issues, let me know. Also be sure to ask in the original repo here: https://github.com/scottlawsonbc/audio-reactive-led-strip

I haven't done much testing with NodeMCU but a ton of people in the original repo have. Good luck! Here's the comparison that I found over on reddit (https://www.reddit.com/r/esp8266/comments/9q3314/nodemcu_v1_v2_v3_size_and_pinout_comparison/) 

![image](https://user-images.githubusercontent.com/8021112/89724271-c502b200-d9ce-11ea-9b8c-7d0f025bd553.png)
