### ISSUE TITLE
error while running sudo python3 visualization.py scroll

### ISSUE THREAD

**Issue by adityadeshpande** [naztronaut/dancyPi-audio-reactive-led#21]
pi@raspberrypi:~/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hos
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
![Annotation 2020-09-05 013812](https://user-images.githubusercontent.com/9282565/92282030-763b3000-ef1a-11ea-9594-ddf9a76c1fae.png)

**Comment by naztronaut** [comment]
Does it keep going or does it error out? Those are warnings and it doesn't look like the app stopped working. Normally on an error, it would take you back to your shell. 

If you look at my demo, I have the exact same warnings at around 6:55: https://youtu.be/7YLF-N0596I?t=415

The app still runs. The warnings can be ignored, it's just some ALSA lib stuff that I know very little about but know that they're just warnings and not exceptions/errors.

**Comment by KarlLouie-14** [comment]
I get the same problem with energy.
But I got the spectrum and scroll to work.

The problem is it gets stuck in:
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

It doesn't start the FPS reading after that.

**Comment by naztronaut** [comment]
That's very strange. What kind of Pi are you using? Can you try turning the display fps to false and try again. It's located here: https://github.com/naztronaut/dancyPi-audio-reactive-led/blob/master/python/config.py#L49

**Comment by KarlLouie-14** [comment]
I'm using a Raspberry Pi 4, and yes I tried setting the display fps to false but still, it doesn't work.
I'll try reinstalling it in another Pi and give you an update. Thanks

**Comment by naztronaut** [comment]
What kind of power source are you using? I wonder if the lights are trying to pull too much power for 'energy' for some reason. Just a theory, doesn't make too much sense since they all work pretty similarly in the background.

**Comment by KarlLouie-14** [comment]
I used the 5V from the Pi to power up the 144 LEDs in the strip. Turns out the reason why it doesnt work is there's not enough current. I tried using an external power supply to power up the LEDs and everything worked. Thanks! 👍

**Comment by naztronaut** [comment]
Awesome! Glad you have it working now. I normally recommend using 2.5A or higher power supply. It's really interesting that it only affected 1/3 of t he visualizations only. 

@adityadeshpande - maybe the issue is the same with you. Let me know if you can try a power supply with more power.

**Comment by adityadeshpande** [comment]
@naztronaut Sorry for being away i got caught up with some other work.

recent findings: 

1. The issue I opened was on my  RPi 2 model B : apparently somehow by GPIO ports ain't working anymore.
2. i bought a new RPi 4 model b (2GB) the code works fine for some 5min's and then the oscillation stops and the LED strip remains stuck to one colour and is non-responsive. (after Reboot): works for 5-6min's and again stops. 

I am using 1Meter 60 LED strip 
RPi is open to air with no enclosure for efficient cooling
i power my strip + Rpi (via gpio) using a 5V1A Adapter

this setup has worked for me on my RPi 2B like smooth - no issues no errors until I burnt my gpio.
so I believe power is not an issue. 
and if it worked on a 512Mb Pi2B it should work on a 2Gb Pi4B as well 

not sure why the led stops responding.

**Comment by adityadeshpande** [comment]
P.s. I also tried on A RPi Version 1 
works fine but 10/50 FPS so I could literally see LED scroll. 
Same power setup, worked fine.

**Comment by naztronaut** [comment]
Sorry to hear about your RPi 2's GPIO ports. Hopefully you can still use it as a server or something that doesn't require the pins. 

As for the Pi 4, the 1A power supply isn't enough. The Pi 4 recommends using at least 2.5A just to power the Pi. When running the code, the Pi itself will probably use the full 1A of the power so that could be why the lights don't work. 

It slightly works on the Pi 1 because it needs less power so there's some left over for the lights. 

I'd recommend either getting a power source with higher current or use an external power source for your lights. Even if you use an external power source, the 1A may not be enough for your Pi 4 to keep it running. 

You can read more about the recommend PSU here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md

**Comment by adityadeshpande** [comment]
Thanks @naztronaut for this, 
I will get a power supply for the Pi 4
And let you know if that works
A quick one. If I use a 2.5A supply, can I still power the raspberry Pi using the GPIO pins? 
I am trying to declutter as much as possible.

**Comment by naztronaut** [comment]
Yeah, that's pretty much what I do on my Pi 3. I don't think there will be much of a difference on the Pi 4 but it's something to keep in mind. I haven't tested this project on a Pi 4 yet. Best of luck and let me know how it goes!

**Comment by adityadeshpande** [comment]
Going for a 3A supply. Will let you know how this works out!

**Comment by adityadeshpande** [comment]
@naztronaut i am using a 3A adaptor, the official CType one that's available for Pi4. Working fine now. That was due to power outage.

**Comment by adityadeshpande** [comment]
Closing issue as we've good understanding of this with different pi's in action. 
Feel free to tag me if you want to know how's it going on Pi4 or other pi's
