### ISSUE TITLE
Install.Py - Collecting pyqtgraph - Not installing - Hanging

### ISSUE THREAD

**Issue by arul24ar** [naztronaut/dancyPi-audio-reactive-led#22]
Install.Py - Collecting pyqtgraph - Not installing - Hanging for long time to install the package. 
Building wheel for scipy (PEP 517) -

**Comment by naztronaut** [comment]
Can you try installing them manually:

```
sudo pip3 install scipy==1.4.1 pyqtgraph
```

Which Pi are you using?

**Comment by arul24ar** [comment]
Hi, I still face the same issue, It is not going beyond  
Building wheel for scipy (PEP 517) 
I m using Raspberry Pi 3

**Comment by naztronaut** [comment]
Try a few other scipy versions, you can find them here: https://pypi.org/project/scipy/#history

By default, I use version 1.4.1 because i found that to work the best. But maybe try the latest versions (1.5.0 to 1.5.2) and see if those install. 

The other thing I can suggest is to just let it run, even if it takes an hour. It has to time out at some point and throw you an error. Once you get an error, it'll be easier to find a solution.

**Comment by arul24ar** [comment]
Tried leaving it for an hour and I got the below message 👍 

"ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

scipy 1.4.1 requires numpy>=1.13.3, but you'll have numpy 1.12.1 which is incompatible.
Successfully installed pyqtgraph-0.11.0 scipy-1.4.1"
 Let me try executing and will reach out to you if I face issues.

**Comment by arul24ar** [comment]
Hi, I get a import module error on pyaudio, Can you please help 
  File "visualization.py", line 7, in <module>
    import microphone
  File "/home/pi/dancyPi-audio-reactive-led/python/microphone.py", line 3, in <module>
    import pyaudio
ImportError: No module named 'pyaudio'

**Comment by naztronaut** [comment]
Numpy, Scipy, Pyqtgraph and Pyaudio are all installed at the same time - in my command above I removed pyaudio just to make sure that wasn't an issue. Just do `sudo pip3 install pyaudio` and that should install the module. 

Also thanks for sharing the error. It's interesting and I wasn't aware of that update, I'll have to do so me testing and make sure my installer can work next month.

**Comment by arul24ar** [comment]
Thank You so much for responding very quickly, I am able to sort out the issues. Now DancyPi in action 👍  , Thank you.

**Comment by naztronaut** [comment]
Awesome! Glad you have it working :) Have fun!
