### ISSUE TITLE
LED Strip is not lighting...dancyPi-audio-reactive-led

### ISSUE THREAD

**Issue by jonib13** [naztronaut/dancyPi-audio-reactive-led#23]
##@Joni B13 If there are no errors then the problem may be hardware. 

How much current is your power source applying?  I usually recommend running at least 2.5A of current if you are powering the lights straight from the Pi. 

WS2812x lights are also directional. Make sure you have them connected the right way. There should be an arrow indicating which way the current should flow. If they are connected backwards then the lights won't turn on. 

Thirdly, make sure your GPIO pins are connected correctly. If you want me to take a look, you can post a comment on Easy Programming or on the GitHub repo where you can post pictures, I'm happy to take a look. Links to both are in the video description.##

----------------------------------------------------------------------------------------------
I have a 12V/33A power supply. I think this should be enough. xD
 
The GPIO pins should be connected correctly. I tried a test with the project of "Core Electronics" (https://core-electronics.com.au/tutor...) and it worked.

The _green_ cable is "Din", I soldered it together with the _green-yellow_ cable. 
The _white_ one is "GND" which I soldered together with the _blue-white_ one.
The red and the white wire go to "V+" and "Common GND" of the power supply.

Where is the quantity of pixels defined?
--------------
![GPIO pins_LI](https://user-images.githubusercontent.com/72999858/96309397-7d6b5880-1005-11eb-8b7d-c92077d97e7a.jpg)
![Raspi GPIO](https://user-images.githubusercontent.com/72999858/96309707-22863100-1006-11eb-9fbc-9fa3665b76ff.jpeg)
![wires Powersupply](https://user-images.githubusercontent.com/72999858/96309714-244ff480-1006-11eb-8d6d-73926519b283.jpeg)
![wires LED strip](https://user-images.githubusercontent.com/72999858/96309718-274ae500-1006-11eb-9079-fcffb977ee97.jpeg)
![LED Strip is working](https://user-images.githubusercontent.com/72999858/96309720-2914a880-1006-11eb-94e1-00d6f63e22b6.jpeg)
--------------

**Comment by jonib13** [comment]
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock


###  I just got this message.  ###

**Comment by naztronaut** [comment]
Thanks for the info! That looks correctly set up. 

I was just about to ask you about your mic when you posted last. What kind of Mic are you using? Alsa errors are typically related to the sound device. 

The mic issue can be one of a few things but most common one that I've seen is the mic_rate. 

In config.py, there's a MIC_RATE constant, by default it's 48000 hz. But the value can range greatly from like 32000 to 192000. I found that 48Khz is common among consumer USB mics so I kept that as the default: Make sure the mic_rate is set correctly: https://github.com/naztronaut/dancyPi-audio-reactive-led#configpy-has-been-edited-as-follows


The second thing could be that the install script didn't pick up the correct sound device. The script inserts the first USB device but it's only accurate most of the time. If you run this command you can see what sound devices your Pi detects:

```
cat /proc/asound/cards
```

By default, it'll set the value of '1'.  If your sound device is not on the value of '1', then change it in alsa.conf and asound.conf. Directions are here: https://github.com/naztronaut/dancyPi-audio-reactive-led#audio-device-configuration

Last thing I'd recommend is unplug your USB, turn off the pi, plug the USB back in, and turn the pi back on. I've noticed that sometimes, newly connected devices aren't recognized properly. And this quick annoying 4 step process seems to help.

**Comment by jonib13** [comment]
i have the Logitech Canada Ices-003 Class B Mic.



![Logitech mic](https://user-images.githubusercontent.com/72999858/96334355-7f1e3600-1070-11eb-81eb-4ba80f192153.jpeg)
![Logitech](https://user-images.githubusercontent.com/72999858/96334357-7fb6cc80-1070-11eb-817e-6c5d8d0bb6c4.jpeg)

**Comment by jonib13** [comment]
I have tried everything and it still does not work. I have set the mic rate to 44100 Hz. I have also followed the other steps you have taken.

**Comment by naztronaut** [comment]
Can you share the outputs of alsa.conf, asound.conf and after running `cat /proc/asound/cards`?  Just want to double check the content. 

The four most important lines in the error are these:

```
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
```

It's saying that it can't find the default device. Although you defined them in the asound.conf and alsa.conf files. So something weird is happening. Can you also try another USB slot? 

I'm currently out of town and don't have access to a Pi. I'll be home next week, I can dig deeper then but until then, I can keep trying to help you as best as I can.

**Comment by jonib13** [comment]
Yes no problem. We will stay on it until we have made it. 

![cat proc_asound_cards](https://user-images.githubusercontent.com/72999858/96351599-caf6cc80-10bc-11eb-976b-8c1f46bb2451.jpeg)

**Comment by naztronaut** [comment]
Your Mic is card 2 but the configs are using card 1. 

In your asound.conf, change those values from card 1 to `card 2` instead. 

And in your alsa.conf, where it says `default.ctl.card 1` and `default.pcm.card 1`, change those to `2` instead. 

Your 'card 1' is your headphones which is why PyAudio can't read that data. Let me know if this helps you move forward. Good luck!

**Comment by jonib13** [comment]
I have adjusted the two things and tried it but it doesn't work.

I have a different error code now.

![Fehler code Raspi](https://user-images.githubusercontent.com/72999858/96743297-2201e780-13c4-11eb-8f34-221bee111aa0.jpeg)

**Comment by naztronaut** [comment]
That's a new error. I did some googling and it seems that error could be because the mic rate doesn't match. Here's a thread from a different project (speech recognition) where the author mentions it: https://github.com/Uberi/speech_recognition/issues/245#issuecomment-349264809

You said you changed the MIC_RATE to 44100, where did you get that value? I'm having trouble finding the datasheet for that mic. Maybe try the default 48000 again and see if that makes a difference.

**Comment by jonib13** [comment]
I started the raspi today and it finally worked.

Thanks for your help, it was my pleasure.
Have a nice week and all the best.
Joni

**Comment by naztronaut** [comment]
Awesome!! Congrats on getting it to work :) I'll close this thread. 

Have fun with the Project!
