### ISSUE TITLE
issue with running the program on a Pi ZeroW

### ISSUE THREAD

**Issue by tylluan24** [naztronaut/dancyPi-audio-reactive-led#28]
Hello! I want to preface this by saying that I have absolutely no programing experience, so this guide has been very helpful. I've run into an issue though.

First off, I am running the setup somewhat unconventionally. I am using a pi zero W. I've found that when I run the microphone off of the USB port of the pi, I don't actually have enough power to boot. My solution is this: run the microphone off of a powered USB bank, and, since I don't have the proper conversion cable, run that powered bank into my unpowered bank which has a micro connector to my pi.

I've found that I am able to plug my keyboard and mouse into the powered bank and use it on the pi just fine, so on some level it's working at least somewhat. After a lot of troubleshooting, I managed to get it to the point where it runs the code just as it shows in the video. 

Here is the problem. The LEDs do not light, and the FPS only updated 3 times before everything just stopped.

What should I do here? Is this just a limitation of the zero? Is there anything I could try to do to fix it? Any help would be appreciated. This was just a "getting my toes wet" sort of project, so it's no big deal if it will be impossible to run on my Zero. Thanks in advance for any assistance!

Attached is a photo of what my command prompt was displaying when it stopped working.
![github example](https://user-images.githubusercontent.com/75287622/100692261-72238080-3358-11eb-87b5-032a97fde2b3.png)

**Comment by naztronaut** [comment]
Hey there, 

Unfortunately, it is a limitation with the Zero :( in my original video, I think I mentioned trying to get it to work on a Pi Zero but failed. Even after I use external power for the lights, the Pi just can't handle the script before it crashes. 

My experience was that the FPS started at 50 and slowly dropped to single digits before becoming unresponsive. Sorry, I don't think there's anything you can do with this project. I need to spend time to figure out where it gets stuck but the Pi Zero just may not have the processing power this project needs so I don't know if it's worth it. 

If you want to get your toes wet with the Pi and WS2812b, I have a couple of other projects that would help:

https://github.com/naztronaut/FCW - Flask Controlled WS2812b - it'll let you control your lights remotely and the code I have is pretty simple so if you do want to get into python, a good place to start might be to change some of the visualizations or create some new ones yourself. 

https://github.com/naztronaut/AIIM - Detects if you're in a meeting on Zoom or Microsoft Teams and triggers lights to be turned on remotely. It requires a python script to be run on your computer as well as a Pi. 

Both projects above work on the Pi Zero.

**Comment by tylluan24** [comment]
Those look awesome! Thanks for the help. It was fun to at least try something out, even if it didn't work out in the end. Thanks man!

**Comment by naztronaut** [comment]
Best of luck! I have other projects and most of them are Pi Zero friendly. This just happens to be the only one that needs to be run on a full Pi. 

More guides here: https://www.easyprogramming.net/raspberrypi.php 

I'm pretty responsive on my site and github if you get stuck.
