### ISSUE TITLE
visualization.py

### ISSUE THREAD

**Issue by szumester** [naztronaut/dancyPi-audio-reactive-led#3]
Hi Champ!

Thanks for this awesome tool! Every time I try to run a visualisation I get the following error message:
Traceback (most recent call last):   File "visualization.py", line 12, in <module>     visType = sys.argv[1] IndexError: list index out of range

Strandtests work without any issues.
Could you help me out? New to programming, so pls be patient :)

Cheers,
Szu

**Comment by naztronaut** [comment]
In my version of the app, `visualization.py` is looking for an argument, either spectrum, energy, or scroll. So if you run the command as follows, it should work:

```
sudo python visualization.py scroll
```
You can substitute `scroll` with either of the two other types and you may or may not need the "sudo". Let me know if that works or if you still have questions. 

You can watch the tutorial video from 19:22 to see how I run it: https://youtu.be/FA9rMkuVmvQ?t=1162

Good luck!

**Comment by naztronaut** [comment]
I'd never dis anyone trying to learn :) 

No input device would also do it. Good luck getting one and hope it works when you do!

Thanks for the suggestion on a small tutorial. I will put that to my backlog. I'll do one where the Pi powers the lights and an other where the lights are powered externally. 

Thanks!

**Comment by szumester** [comment]
Hi Champ,

For some reason the visualization didn't work without the mic, once I attached it worked like charm!
I'll try to get Libs to import more vis Styles. 
Any experience with Jack Audio for creating a virtual sound card? Would be nice if I could use the music played on the pi for input not only the Mic.

Thanks for the help once more and have a splendid day! :)
Zsolt

**Comment by Tim-Dixon** [comment]
Before I finally gave in and purchased the USB audio adapter, I attempted to get Jack and Pulse Audio working on the Pi. I was able to get Pulse Audio working, as it seemed easier than Jack, but I used the pavucontrol package which provides a GUI for Pulse Audio Control, in which I was able to configure a loopback device. The visualization.py program did take the sound input from Spotify in my browser on Pi Desktop, however it would quickly quit playing any visualizations, including the strandtest. It seemed to be an issue with the X Server running. I opened an issue with Scott's repo about it but haven't heard back. Booting into the CLI first and running everything worked fine, but I couldn't use the Pulse Audio Control GUI to link the peripherals anymore. I have yet to determine how to configure it via the CLI. If I make any progress, I'll let you know. My personal goal is to allow bluetooth to the Pi for audio in, the on board audio out to a speaker, and internally, of course using Pulse or Jack, the visualization.py would be able to receive the audio input as well. This then allows a truly plug and play headless setup, which is what I'm looking for. We'll see how it goes XD

**Comment by NickSutton** [comment]
> Before I finally gave in and purchased the USB audio adapter, I attempted to get Jack and Pulse Audio working on the Pi. I was able to get Pulse Audio working, as it seemed easier than Jack, but I used the pavucontrol package which provides a GUI for Pulse Audio Control, in which I was able to configure a loopback device. The visualization.py program did take the sound input from Spotify in my browser on Pi Desktop, however it would quickly quit playing any visualizations, including the strandtest. It seemed to be an issue with the X Server running. I opened an issue with Scott's repo about it but haven't heard back. Booting into the CLI first and running everything worked fine, but I couldn't use the Pulse Audio Control GUI to link the peripherals anymore. I have yet to determine how to configure it via the CLI. If I make any progress, I'll let you know. My personal goal is to allow bluetooth to the Pi for audio in, the on board audio out to a speaker, and internally, of course using Pulse or Jack, the visualization.py would be able to receive the audio input as well. This then allows a truly plug and play headless setup, which is what I'm looking for. We'll see how it goes XD

This is exactly what I’ve been trying to achieve. I am using the awesome [https://github.com/mikebrady/shairport-sync](url) shairport-sync software which allows me to send audio from my iPhone over airplay to the Pi.

It seems crazy that to receive audio AND blink some LEDs I need one Pi to do each task, with one just listening to the audio output via USB mic!

I was looking in to loop backs within PyAudio and also `sudo modprobe snd aloop` To create a loop back device within ALSA, but no progress to report.

Even running visualition.py, then starting to send audio over Shairport-Sync results in the vis crashing.

I feel like a loop back device configured as the default audio input should be the way to go, but I also need my audio output to continue to be fed to my audio HAT then speakers.

Please do let us know if you make any progress!
