### ISSUE TITLE
Visualization.py rennt auf Fehler

### ISSUE THREAD

**Issue by djmax9999** [naztronaut/dancyPi-audio-reactive-led#32]
Hallo,

ich habe die Anleitung von Dir abgearbeitet und über Dein Setup Script installiert. 
An meinem Raspberry 3b Plus sind insgesamt 4 LED Strips mit 503 LED angeschlossen. Externe Stromversorgung für jeden Strip.
Zusätzlich eine USB Soundkarte und ein Headset mit 3,5 Klinke für Lautsprecher und Mikrofon. Die Soundkarte funktioniert einwandfrei; getestet mit  aplay und arecord. Das Mikrofon liegt direkt auf dem Echo DOT.

Wenn ich jetzt python3 visualization.py scroll ausführe kommen folgende Fehlermeldungen:

 pi@raspberrypi:~/dancyPi-audio-reactive-led/python $ sudo python3 visualization.py scroll
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x82 AES2 0x0 AES3 0x2  CARD 1}
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "visualization.py", line 368, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/dancyPi-audio-reactive-led/python/microphone.py", line 22, in start_stream
    callback(y)
  File "visualization.py", line 229, in microphone_update
    led.update()
  File "/home/pi/dancyPi-audio-reactive-led/python/led.py", line 144, in update
    _update_pi()
  File "/home/pi/dancyPi-audio-reactive-led/python/led.py", line 105, in _update_pi
    if np.array_equal(p[:, i], _prev_pixels[:, i]):
IndexError: index 502 is out of bounds for axis 1 with size 502

was mach ich falsch ??

Danke für Deine Hilfe...
Gruß,
Max

**Comment by naztronaut** [comment]
Hallo Max,

Ich spreche kein Deutsch und habe Ihre Nachricht in Google Translate übersetzt.

Können Sie den folgenden Befehl ausführen und die Ausgabe freigeben:

```
cat /proc/asound/cards
```

Lass mich wissen, was du siehst.

**Comment by djmax9999** [comment]
Hi, so let´s continue in english if it´s easier for you.... ;-)

 1 [Set            ]: USB-Audio - C-Media USB Headphone Set
                      C-Media USB Headphone Set at usb-3f980000.usb-1.3, full speed

**Comment by naztronaut** [comment]
Thanks, Max :)

Is that the only thing that displays? Your Echo DOT isn't appearing on the list so the app isn't picking up the microphone. You mentioned you ran aplay and arecord already. Can you share the output of that here?

```
aplay -l
arecord -l
```

Thanks!

**Comment by djmax9999** [comment]
ok, here we are:
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

arecord -l
card 1: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by djmax9999** [comment]
To be more concrete regarding the Echo:

I´ve put the microphone of the connected headset on top of the Echo DOT to get clear input from the Echo Speaker.
I did not connect the Dot to the Raspi...

**Comment by djmax9999** [comment]
It works as designed..... My problem was the Index of 503 LEDs.

I´ve set the N_PIXELS = 500 and it works pretty fine :-)

So this issue is gets "closed"

**Comment by naztronaut** [comment]
Ah yes, it needs to be an even number of LEDs because the math divides by 2 and is looking for an integer. Sorry I missed that in the original post. 

Glad you were able to figure it out :) Have fun with it!
